// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtzKMBrCk79f2bbCs9AvdhPM9pYxGurw',
    appId: '1:309395307875:web:5e99f97f9f94fe177de756',
    messagingSenderId: '309395307875',
    projectId: 'fir-with-f1885',
    authDomain: 'fir-with-f1885.firebaseapp.com',
    storageBucket: 'fir-with-f1885.appspot.com',
    measurementId: 'G-2J9PD5PDG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5QzCe-LD1Sm2sYRgTA5_1yK3o6ddkQPc',
    appId: '1:309395307875:android:e14e48f92c353da27de756',
    messagingSenderId: '309395307875',
    projectId: 'fir-with-f1885',
    storageBucket: 'fir-with-f1885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBvia5u-Y_eT8Ahqj9r_wuk5OH57OYN4',
    appId: '1:309395307875:ios:2b08d7dd43c697417de756',
    messagingSenderId: '309395307875',
    projectId: 'fir-with-f1885',
    storageBucket: 'fir-with-f1885.appspot.com',
    iosBundleId: 'com.example.googlelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOBvia5u-Y_eT8Ahqj9r_wuk5OH57OYN4',
    appId: '1:309395307875:ios:f4e7d6fff2010a5c7de756',
    messagingSenderId: '309395307875',
    projectId: 'fir-with-f1885',
    storageBucket: 'fir-with-f1885.appspot.com',
    iosBundleId: 'com.example.googlelogin.RunnerTests',
  );
}
